spec-version: v2

# Required: A short name for the action package
name: Knowledge Base Access

# Required: A description of what's in the action package.
description: Actions for accessing a Sema4.ai Knowledge Base.

# Package version number, recommend using semver.org
version: 1.0.0

dependencies:
  conda-forge:
  - python=3.11.11
  - uv=0.6.11
  pypi:
  - sema4ai-actions=1.4.1
  - sema4ai-data=1.0.7

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_store/**
  - ./**/*.pyc
  - ./**/*.zip
  - ./**/.env
