# For more details on the format and content:
# https://github.com/joshyorko/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.11 # https://anaconda.org/conda-forge/python
  - uv=0.8.17 # https://anaconda.org/conda-forge/uv
  - pip:
      - robocorp==3.0.0 # https://pypi.org/project/robocorp
      - robocorp-truststore==0.9.1 # https://pypi.org/project/robocorp-truststore
      - rpaframework-assistant==5.0.0 # https://pypi.org/project/rpaframework-assistant
      - requests==2.32.5 # https://pypi.org/project/requests
      - gitpython==3.1.46 # https://pypi.org/project/GitPython
      - pandas==2.3.3 # https://pypi.org/project/pandas
      - beautifulsoup4==4.14.3 # https://pypi.org/project/beautifulsoup4
      - jinja2==3.1.6 # https://pypi.org/project/Jinja2
      - redis==7.1.0 # https://pypi.org/project/redis
      - psycopg2-binary==2.9.11 # https://pypi.org/project/psycopg2-binary
      - SQLAlchemy==2.0.45 # https://pypi.org/project/SQLAlchemy
      - pymongo==4.15.5 # https://pypi.org/project/pymongo
      - robocorp-adapters-custom==0.1.4 # https://pypi.org/project/robocorp-adapters-custom
