blank_issues_enabled: true
version: 2.1
contact_links:
  - name: 🤔 Idea or question?
    url: http://sema4ai-users.slack.com/
    about: Join our Community Slack for more in-depth discussions.
  - name: 🚨 Report a Security Vulnerability
    about: Please refer to our security policy for more details.
    url: https://robocorp.com/security
