# Required: A short name for the action package
name: data-predict-template

# Required: A description of what's in the action package.
description: Actions showcasing the predictive model capabilities of the Sema4.ai Data Access

# Package version number, recommend using semver.org
version: 0.0.1

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.8
    - sema4ai-data=1.0.2

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
