# Required: A short name for the action package
name: Minimal Template Package

# Required: A description of what's in the action package.
description: Action package description

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.2.4
  pypi:
  - sema4ai-actions=0.8.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ".*" # Excludes all hidden files
    - ./**/*.pyc
    - ./**/*.zip