spec-version: v2

# Required: A short name for the action package
name: Minimal Template Package

# Required: A description of what's in the action package.
description: Action package description

# Package version number, recommend using semver.org
version: 0.0.1

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.13

dev-dependencies:
  conda-forge:
    - pytest=8.3.5
    - types-requests=2.32.0.20250301
    - ruff=0.11.12
    - mypy=1.16.0

dev-tasks:
  test: pytest tests
  lint: |
    ruff check .
    ruff format --check .
  typecheck: mypy --follow-imports=silent --strict .
  prettify: |
    ruff format .

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
    - ./**/__MACOSX
    - ./**/__pycache__
    - ./**/.git
    - ./node_modules/**
