# Nice reference: https://github.com/tornadoweb/tornado/blob/master/.github/workflows/build.yml
# Docs: https://cibuildwheel.readthedocs.io/en/stable/options/
# Configurations are here and in pyproject.toml.
name: Action Server [MANYLINUX] Release

on:
  push:
    #     branches:
    #       - "wip-manylinux"

    tags:
      - "sema4ai-action_server-*"

defaults:
  run:
    working-directory: "./action_server"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-15]
    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@robocorp"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.23.1
          python -m pip install invoke
          python -m invoke build-frontend
          python -m invoke build-oauth2-config
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT_READ_PACKAGES }}
          GH_TOKEN: ${{ secrets.GH_PAT_GHA_TO_ANOTHER_REPO }}

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: pp*
          CIBW_BUILD: cp312-*macos*arm64 cp312-*manylinux*x86_64 cp312-*win*amd64 cp313-*macos*arm64 cp313-*manylinux*x86_64 cp313-*win*amd64
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-wheels
          path: "action_server/wheelhouse/*"

      - name: Upload to PyPI .whl
        run: |
          pip install twine
          twine upload wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_SEMA4AI_ACTION_SERVER }}
