name: Action Server [BINARY] Release

on:
  workflow_dispatch:
    # Enables manual triggering via GitHub Actions

  push:
    branches:
      - wip
    tags:
      - "sema4ai-action_server-*"

defaults:
  run:
    working-directory: "./action_server"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Important: Changing os requires updating the related references in this yml.
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            asset_path: action_server/dist/final/action-server

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@robocorp"

      - name: Install build requirements
        run: |
          python -m pip install poetry
          python -m pip install invoke
          python -m invoke build-frontend
          python -m invoke build-oauth2-config
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT_READ_PACKAGES }}
          GH_TOKEN: ${{ secrets.GH_PAT_GHA_TO_ANOTHER_REPO }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build binary
        run: |
          poetry install
          poetry run inv build-executable --sign --go-wrapper --version=0.0.1-local
        env:
          RC_ACTION_SERVER_FORCE_DOWNLOAD_RCC: true
          RC_ACTION_SERVER_DO_SELFTEST: true

          MACOS_SIGNING_CERT: ${{ secrets.MACOS_SIGNING_CERT_SEMA4AI }}
          MACOS_SIGNING_CERT_PASSWORD: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD_SEMA4AI }}
          MACOS_SIGNING_CERT_NAME: ${{ secrets.MACOS_SIGNING_CERT_NAME_SEMA4AI }}

          APPLEID: ${{ secrets.MACOS_APP_ID_FOR_NOTARIZATION_SEMA4AI }}
          APPLETEAMID: ${{ secrets.MACOS_TEAM_ID_FOR_NOTARIZATION_SEMA4AI }}
          APPLEIDPASS: ${{ secrets.MACOS_APP_ID_PASSWORD_FOR_NOTARIZATION_SEMA4AI }}

          VAULT_URL: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_URL_SEMA4AI }}
          CLIENT_ID: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_ID_SEMA4AI }}
          TENANT_ID: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_TENANT_ID_SEMA4AI }}
          CLIENT_SECRET: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_SECRET_SEMA4AI }}
          CERTIFICATE_NAME: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CERTIFICATE_NAME_SEMA4AI }}

          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

      - uses: actions/upload-artifact@v4
        with:
          name: action-server-${{ matrix.os }}
          path: ${{ matrix.asset_path }}

      - name: Run executable
        run: |
          ./dist/final/action-server
